version: '3'

volumes:
  local_postgres_data: {}
  local_mongo_data: {}
  local_postgres_data_backups: {}
  node_modules: {}

services:
  postgres:
    image: postgres
    container_name: cesiPostgres
    volumes:
      - local_postgres_data:/var/lib/postgresql/data
      - local_postgres_data_backups:/backups
    env_file:
      - ./envs/local/.postgres
    ports:
      - "5432:5432"


  frontend:
    build:
      context: .
      dockerfile: ./Docker/local/frontend/Dockerfile
    image: cesi_logiciel_local_frontend
    container_name: frontend
    volumes:
      - ./frontend:/app:z
      # http://jdlm.info/articles/2016/03/06/lessons-building-node-app-docker.html
      - ./frontend/node_modules:/app/node_modules
    command: npm run dev
    ports:
      - "3000:3000"

  mongo:
    container_name: mongo-dev
    image: mongo:latest
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_DATABASE=auth
      - MONGO_INITDB_ROOT_PASSWORD=pass
    ports:
      - '48151:27017'
    volumes: 
      - local_mongo_data:/data/db
  
    
  Microservices:
    build:
      context: .
      dockerfile: ./Docker/local/backend/Microservices/Dockerfile
    image: cesi_logiciel_local_backend_microservices
    container_name: microservices
    depends_on:
      - mongo
      - postgres
    volumes:
      - ./backend/microservices:/app:z
      # http://jdlm.info/articles/2016/03/06/lessons-building-node-app-docker.html
      - ./backend/Microservices/node_modules:/app/node_modules
    command: npm run dev
    ports:
      - "6060:6060"

  API:
    build:
      context: .
      dockerfile: ./Docker/local/backend/API/Dockerfile
    image: cesi_logiciel_local_backend_api
    container_name: API
    depends_on:
      - mongo
      - postgres
    volumes:
      - ./backend/api:/app:z
      # http://jdlm.info/articles/2016/03/06/lessons-building-node-app-docker.html
      - ./backend/API/node_modules:/app/node_modules
    command: npm run dev
    ports:
      - "8080:8080"